package com.example.testspring4;

import org.hibernate.resource.jdbc.spi.StatementInspector;

import java.util.List;
import java.util.concurrent.CopyOnWriteArrayList;

/**
 * Captures SQL statements generated by Hibernate so a test can assert on the generated query.
 *
 * <p>Registered via {@code hibernate.session_factory.statement_inspector} (see
 * {@code application.properties}). Hibernate instantiates it, so the captured statements are kept
 * in a static registry shared with the tests.</p>
 */
public class SqlStatementCapture implements StatementInspector {

	private static final List<String> STATEMENTS = new CopyOnWriteArrayList<>();

	@Override
	public String inspect(String sql) {
		STATEMENTS.add(sql);
		return sql;
	}

	public static void clear() {
		STATEMENTS.clear();
	}

	public static List<String> statements() {
		return List.copyOf(STATEMENTS);
	}

	/**
	 * Returns the first captured statement that contains the given (case-insensitive) fragment.
	 */
	public static String firstContaining(String fragment) {
		return STATEMENTS.stream()
				.filter(sql -> sql.toLowerCase().contains(fragment.toLowerCase()))
				.findFirst()
				.orElse(null);
	}
}
